name: Clang Format Check

on: pull_request

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get -y install clang-format-14
    - name: Run clang-format-check
      run: sh external/misc/clang-format-check.sh
    